spring:
  datasource:
    url: jdbc:mysql://j9a102.p.ssafy.io/ssafety?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: a102
    password: ssafy102
#    url: jdbc:mysql://localhost:3306/ssafety
#    username: a102
#    password: a102
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  jackson:
    serialization:
      write-dates-as-timestamps: false
      write-date-timestamps-as-nanoseconds: false
server:
  port: 8080
cloud:
  aws:
    credentials:
      accessKey: aws access key
      secretKey: aws secret key
    region:
      static: ap-northeast-2
    stack:
      auto: false

kakao:
  api:
    key: kakao api key

logging:
  level:
    org.springframework: debug
    org.hibernate.SQL: DEBUG

naver-cloud-sms:
  accesskey: naver colud sms access key
  secretkey: naver colud sms secret key
  serviceId: naver colud sms service id
  phone: phone num
